### PR TITLE
Pillow version

### PR DESCRIPTION
**Pull request by jburel**
Change pillow version to match requirements file (omeroweb)

### CODE REVIEW

**Comment by manics** [comment]
Looks fine in principle. Either we can ignore travis for now (it's failing because galaxy roles aren't installed), or add a molecule test. If you want to do the latter the test infrastructure from https://github.com/openmicroscopy/ansible-role-java is probably a good one to start from

**Comment by atarkowska** [comment]
We don't need to pip install any more, could you please remove pip section and use python-pillow now? see https://github.com/ome/omero-install/pull/129

**Comment by jburel** [comment]
Do we want follow the same approach for pillow that the one for python-pip
i.e. see https://github.com/openmicroscopy/ansible-role-omero-python-deps/blob/master/tasks/main.yml and https://github.com/openmicroscopy/ansible-role-omero-python-deps/blob/master/tasks/pypi.yml#L15
?

**Comment by atarkowska** [comment]
yes but I think package is names `python-yaml` rather then `PyYAML` or that is the same? At least that is what was tested with omero-install

**Comment by jburel** [comment]
I am looking at https://github.com/openmicroscopy/ansible-role-omero-python-deps/blob/master/tasks/main.yml#L22
and 
https://github.com/openmicroscopy/ansible-role-omero-python-deps/blob/master/tasks/pypi.yml#L15

**Comment by jburel** [comment]
``python-pillow`` is installed if ``distribution`` is set
``pillow`` is installed via pip if ``pypi`` is set
so I think it follows the decision
unless we completely want to remove the "pypi" parameter

**Comment by jburel** [comment]
Discussed today, I will remove the "pip" installation.
Closing this PR

**Pull request closed without merging**
